#pragma config(Sensor, in1,    claw_s,         sensorPotentiometer)
#pragma config(Sensor, in3,    gyro,           sensorGyro)
#pragma config(Sensor, in6,    claw_s2,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  arms_s,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  right,          sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  button,         sensorTouch)
#pragma config(Motor,  port1,           ArmR1,         tmotorVex393HighSpeed_HBridge, openLoop)
#pragma config(Motor,  port2,           ArmR2,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ArmR3,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           ClawA,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           ClawB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           DriveL,        tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           DriveR,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           ArmL1,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           ArmL2,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          ArmL3,         tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

int claw;
int arms;
float target;
float error;
float Kp = 0.9;
float Ki = 0;
float Kd = 0;
bool close;
// 0.002, 0.001, 0.002;
const short leftButton = 1;
const short centerButton = 2;
const short rightButton = 4;
int count = 0;
//Manitha stuff
int claw_;


void gyro_turnManitha(int degrees10)
{
	int motorpower = 1;
	bool negative;
	bool done = false;
	SensorValue[in3] = 0;
	if (degrees10 > 0) {
		negative = false;
		} else {
		negative = true;
	}
	while(negative == false && done == false) {
		if(motorpower == 0) {
			motor[DriveR] = 0;
			motor[DriveL] = 0;
			done = true;
		}
		else {
			while(abs(SensorValue[in3]) < degrees10 - 100) {
				motor[DriveL] = 50;
				motor[DriveR] = -50;
			}
			motor[DriveR] = -5;
			motor[DriveL] = 5;
			motorpower = (SensorValue[in3] - degrees10)*0.25;
			wait1Msec(50);
			if (motorpower < 40 && motorpower > -40 && motorpower != 0) {
				motorpower = 0;
			}
			motor[DriveL] = (-motorpower - motorpower)*0.4;
			motor[DriveR] = (motorpower + motorpower)*0.4;
			wait1Msec(100);
		}
	}
	while(negative ==
		true && done == false) {
		if(motorpower == 0) {
			motor[DriveR] = 0;
			motor[DriveL] = 0;
			done = true;
		}
		else {
			while(SensorValue[in3] > degrees10 + 100) {
				motor[DriveL] = -50;
				motor[DriveR] = 50;
			}
			motor[DriveR] = 5;
			motor[DriveL] = -5;
			motorpower = (SensorValue[in3] - degrees10)*0.25;
			wait1Msec(50);
			if (motorpower < 40 && motorpower > -40 && motorpower != 0) {
				motorpower = 0;
			}
			motor[DriveL] = (-motorpower - motorpower)*0.4;
			motor[DriveR] = (motorpower + motorpower)*0.4;
			wait1Msec(100);
		}
	}
}

void waitForPress()
{
	while(nLCDButtons == 0){}
	wait1Msec(5);
}

void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}

void threeStars(int masterPower, int left_ticks) {
	int totalTicks = 0;
	int Autoerror = 0;
	int slavePower = masterPower - 5;
	SensorValue[arms_s] = 0;
	SensorValue[right] = 0;
	SensorValue[left] = 0;
	while(abs(totalTicks) < left_ticks) {
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;

		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		motor[ClawB] = (1520 - claw_r)*-0.05 - claw_d_r*0.2;
		motor[ClawA] = (1520 - claw_l)*-0.05 - claw_d_l*0.2;
		target = 800;
		error = target - SensorValue[arms_s];
		arms = (Kp*error);
		motor[ArmR1] = arms;
		motor[ArmR2] = arms;
		motor[ArmR3] = arms;
		motor[ArmL1] = arms;
		motor[ArmL2] = arms;
		motor[ArmL3] = arms;

		motor[DriveL] = masterPower;
		motor[DriveR] = slavePower;

		Autoerror = (abs(SensorValue[left]) - SensorValue[right]);
		slavePower += Autoerror * 0.5;
		totalTicks += abs(SensorValue[left]);
		SensorValue[right] = 0;
		SensorValue[left] = 0;
		wait1Msec(100);
	}
	while(true) {
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;

		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		target = 730;
		error = target - SensorValue[arms_s];
		arms = (Kp*error);
				motor[ClawB] = (1520 - claw_r)*-0.05 - claw_d_r*0.2;
		motor[ClawA] = (1520 - claw_l)*-0.05 - claw_d_l*0.2;
		motor[ArmR1] = arms;
		motor[ArmR2] = arms;
		motor[ArmR3] = arms;
		motor[ArmL1] = arms;
		motor[ArmL2] = arms;
		motor[ArmL3] = arms;
	}
	motor[DriveL] = 0;
	motor[DriveR] = 0;
}

void CubeTurn(int degrees10) {
	target = 280;
	SensorValue[arms_s] = 0;
	int motorpower = 1;
	bool negative;
	int clawValue;
	bool done = false;
	SensorValue[in3] = 0;
	if (degrees10 > 0) {
		negative = false;
		} else {
		negative = true;
	}
	while(SensorValue[in1] < 150) {
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;
		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		motor[ClawB] = (100 - claw_r)*-0.05 - claw_d_r*0.2;
		motor[ClawA] = (100 - claw_l)*-0.05 - claw_d_l*0.2;
	}
	wait1Msec(500);
	while(negative == false && done == false) {
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;
		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		motor[ClawB] = (100 - claw_r)*-0.05 - claw_d_r*0.2;
		motor[ClawA] = (100 - claw_l)*-0.05 - claw_d_l*0.2;
		error = target - SensorValue[arms_s];
		arms = (Kp*error);
		motor[ArmR1] = arms;
		motor[ArmR2] = arms;
		motor[ArmR3] = arms;
		motor[ArmL1] = arms;
		motor[ArmL2] = arms;
		motor[ArmL3] = arms;
		if(motorpower == 0) {
			motor[DriveR] = 0;
			motor[DriveL] = 0;
			done = true;
		}
		else {
			while(abs(SensorValue[in3]) < degrees10 - 100) {
				motor[DriveL] = 40;
				motor[DriveR] = -40;
				int	claw_r = SensorValue[in1] + 0;
				int claw_l = SensorValue[in6] + 50;
				int claw_r_save = claw_r;
				int claw_l_save = claw_l;
				wait1Msec(100);
				int claw_d_r = claw_r - claw_r_save;
				int claw_d_l = claw_l - claw_l_save;
				motor[ClawB] = (100 - claw_r)*-0.05 - claw_d_r*0.2;
				motor[ClawA] = (100 - claw_l)*-0.05 - claw_d_l*0.2;
				error = target - SensorValue[arms_s];
				arms = (Kp*error);
				motor[ArmR1] = arms;
				motor[ArmR2] = arms;
				motor[ArmR3] = arms;
				motor[ArmL1] = arms;
				motor[ArmL2] = arms;
				motor[ArmL3] = arms;
			}
			int	claw_r = SensorValue[in1] + 0;
			int claw_l = SensorValue[in6] + 50;
			int claw_r_save = claw_r;
			int claw_l_save = claw_l;
			wait1Msec(100);
			int claw_d_r = claw_r - claw_r_save;
			int claw_d_l = claw_l - claw_l_save;
			motor[ClawB] = (100 - claw_r)*-0.05 - claw_d_r*0.2;
			motor[ClawA] = (100 - claw_l)*-0.05 - claw_d_l*0.2;
			motor[DriveR] = -5;
			motor[DriveL] = 5;
			motorpower = (SensorValue[in3] - degrees10)*0.25;
			wait1Msec(50);
			if (motorpower < 20 && motorpower > -20 && motorpower != 0) {
				motorpower = 0;
			}
			motor[DriveL] = (-motorpower - motorpower)*0.25;
			motor[DriveR] = (motorpower + motorpower)*0.25;
			wait1Msec(100);
		}
	}
	while(negative == true && done == false) {
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;
		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		error = target - SensorValue[arms_s];
		arms = (Kp*error);
		motor[ClawB] = (100 - claw_r)*-0.05 - claw_d_r*0.2;
		motor[ClawA] = (100 - claw_l)*-0.05 - claw_d_l*0.2;
		motor[ArmR1] = arms;
		motor[ArmR2] = arms;
		motor[ArmR3] = arms;
		motor[ArmL1] = arms;
		motor[ArmL2] = arms;
		motor[ArmL3] = arms;
		if(motorpower == 0) {
			motor[ClawA] = 60;
			motor[ClawB] = 60;
			motor[DriveR] = 0;
			motor[DriveL] = 0;
			done = true;
		}
		else {
			while(SensorValue[in3] > degrees10 + 100) {
				int	claw_r = SensorValue[in1] + 0;
				int claw_l = SensorValue[in6] + 50;
				int claw_r_save = claw_r;
				int claw_l_save = claw_l;
				wait1Msec(100);
				int claw_d_r = claw_r - claw_r_save;
				int claw_d_l = claw_l - claw_l_save;
				motor[ClawB] = (100 - claw_r)*-0.05 - claw_d_r*0.2;
				motor[ClawA] = (100 - claw_l)*-0.05 - claw_d_l*0.2;
				motor[DriveL] = -40;
				motor[DriveR] = 40;
				error = target - SensorValue[arms_s];
				arms = (Kp*error);
				motor[ClawA] = 50;
				motor[ClawB] = 50;
				motor[ArmR1] = arms;
				motor[ArmR2] = arms;
				motor[ArmR3] = arms;
				motor[ArmL1] = arms;
				motor[ArmL2] = arms;
				motor[ArmL3] = arms;
			}
			motor[DriveR] = 5;
			motor[DriveL] = -5;
			motorpower = (SensorValue[in3] - degrees10)*0.25;
			wait1Msec(50);
			if (motorpower < 20 && motorpower > -20 && motorpower != 0) {
				motorpower = 0;
			}
			int	claw_r = SensorValue[in1] + 0;
			int claw_l = SensorValue[in6] + 50;
			int claw_r_save = claw_r;
			int claw_l_save = claw_l;
			wait1Msec(100);
			int claw_d_r = claw_r - claw_r_save;
			int claw_d_l = claw_l - claw_l_save;
			motor[ClawB] = (100 - claw_r)*-0.05 - claw_d_r*0.2;
			motor[ClawA] = (100 - claw_l)*-0.05 - claw_d_l*0.2;
			motor[DriveL] = (-motorpower - motorpower)*0.25;
			motor[DriveR] = (motorpower + motorpower)*0.25;
			wait1Msec(100);
		}
	}
	motor[DriveL] = 0;
	motor[DriveR] = 0;
	motor[ClawA] = 0;
	motor[ClawB] = 0;
}

void clawOpenV() {
	while(SensorValue[in1] > 1800) {
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;

		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		motor[ClawB] = (1520 - claw_r)*-0.05 - claw_d_r*0.2;
		motor[ClawA] = (1520 - claw_l)*-0.05 - claw_d_l*0.2;
	}
	motor[ClawA] = 0;
	motor[ClawB] = 0;
}

void clawOpen() {
	while(SensorValue[in1] > 2000) {
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;

		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		motor[ClawB] = (1520 - claw_r)*-0.05 - claw_d_r*0.2;
		motor[ClawA] = (1520 - claw_l)*-0.05 - claw_d_l*0.2;
	}
	motor[ClawA] = 0;
	motor[ClawB] = 0;
}

task clawControl() {
	int clawValue;
	while(true) {
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;

		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		if(vexRT[Btn5U] == 1)
		{
			clawValue = 100;
		}
		if(vexRT[Btn5D] == 1)
		{
			clawValue = 1520;
		}
		if(vexRT[Btn8D] == 1) {
			clawValue = 2860;
		}
		if(vexRT[Btn7U] == 0)
		{
			motor[ClawB] = (clawValue - claw_r)*-0.05 - claw_d_r*0.2;
			motor[ClawA] = (clawValue - claw_l)*-0.05 - claw_d_l*0.2;
		}
	}
}

task arm() {
	while(true) {
		if (vexRT[Btn7R] == 1) {
			target = 350;
			SensorValue[arms_s] = 0;
			while(vexRT[Btn6U] == 0) {
				motor[ClawA] = 70;
				motor[ClawB] = 70;
				error = target - SensorValue[arms_s];
				arms = (Kp*error);
			}
		}
		while (vexRT[Btn6U] == 1) {
			arms = 127;
		}
		while(vexRT[Btn6D] == 1 && SensorValue[button] == 0) {
			arms = -127;
		}
		arms = 0;
	}
}

task drive() {
	bool typeDrive = true;
	while(true) {
		while(typeDrive == true) {
			motor[DriveL] = vexRT[Ch2];
			motor[DriveR] = vexRT[Ch3];
			if (vexRT[Btn7D] == 1) {
				typeDrive = false;
			}
		}
		while(typeDrive == false) {
			motor[DriveL] = vexRT[Ch2] - vexRT[Ch1];
			motor[DriveR] = vexRT[Ch2] + vexRT[Ch1];
			arms = vexRT[Ch3];
			if (vexRT[Btn7L] == 1) {
				typeDrive = true;
			}
		}
	}
}
void autoDriveTicksShaftPower(int masterPower, int left_ticks) { //Drive forward based on sensor values.
	int totalTicks = 0;
	int Autoerror = 0;
	int slavePower = masterPower - 5;
	bool type_drive;

	SensorValue[right] = 0;
	SensorValue[left] = 0;

	if (left_ticks > 0) {
		type_drive = true;
		} else {
		type_drive = false;
	}
	if (type_drive == true) {
		while(abs(totalTicks) < left_ticks) {
			int	claw_r = SensorValue[in1] + 0;
			int claw_l = SensorValue[in6] + 50;
			int claw_r_save = claw_r;
			int claw_l_save = claw_l;
			wait1Msec(100);
			int claw_d_r = claw_r - claw_r_save;
			int claw_d_l = claw_l - claw_l_save;
			motor[ClawB] = (100 - claw_r)*-0.05 - claw_d_r*0.2;
			motor[ClawA] = (100 - claw_l)*-0.05 - claw_d_l*0.2;
			motor[DriveL] = masterPower;
			motor[DriveR] = slavePower;

			Autoerror = (abs(SensorValue[left]) - SensorValue[right]);
			slavePower += Autoerror * 0.5;
			totalTicks += abs(SensorValue[left]);
			SensorValue[right] = 0;
			SensorValue[left] = 0;
			wait1Msec(100);
		}
		motor[DriveL] = 0;
		motor[DriveR] = 0;
	}

	if (type_drive == false) {
		while(totalTicks > left_ticks) {
			motor[ClawA] = 70;
			motor[ClawB] = 70;
			motor[DriveL] = masterPower;
			motor[DriveR] = slavePower;

			Autoerror = (SensorValue[left] - SensorValue[right]);
			slavePower += Autoerror * 0.5;
			totalTicks += SensorValue[left];
			SensorValue[right] = 0;
			SensorValue[left] = 0;
			wait1Msec(100);
		}
		motor[DriveL] = 0;
		motor[DriveR] = 0;
	}
}

void autoDownMove(int masterPower, int left_ticks) {
	int totalTicks = 0;
	int Autoerror = 0;
	int slavePower = masterPower - 5;
	bool type_drive;
	int clawValue;
	while(SensorValue[in1] > 2000) {
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;

		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		motor[ClawB] = (1520 - claw_r)*-0.05 - claw_d_r*0.2;
		motor[ClawA] = (1520 - claw_l)*-0.05 - claw_d_l*0.2;
	}
	while(SensorValue[button] == 0) {
		motor[ArmL1] = -100;
		motor[ArmL2] = -100;
		motor[ArmL3] = -100;
		motor[ArmR1] = -100;
		motor[ArmR2] = -100;
		motor[ArmR3] = -100;
	}

	motor[ClawB] = 0;
	motor[ClawA] = 0;
	motor[ArmL1] = 0;
	motor[ArmL2] = 0;
	motor[ArmL3] = 0;
	motor[ArmR1] = 0;
	motor[ArmR2] = 0;
	motor[ArmR3] = 0;

	SensorValue[right] = 0;
	SensorValue[left] = 0;
	if (left_ticks > 0) {
		type_drive = true;
		} else {
		type_drive = false;
	}
	if (type_drive == true) {
		while(abs(totalTicks) < left_ticks) {
			motor[DriveL] = masterPower;
			motor[DriveR] = slavePower;

			Autoerror = (abs(SensorValue[left]) - SensorValue[right]);
			slavePower += Autoerror * 0.5;
			totalTicks += abs(SensorValue[left]);

			SensorValue[right] = 0;
			SensorValue[left] = 0;
			wait1Msec(100);
		}
		motor[DriveL] = 0;
		motor[DriveR] = 0;
	}

	if (type_drive == false) {
		while(totalTicks > left_ticks) {
			motor[DriveL] = masterPower;
			motor[DriveR] = slavePower;

			Autoerror = (SensorValue[left] - SensorValue[right]);
			slavePower += Autoerror * 0.5;
			totalTicks += SensorValue[left];
			SensorValue[right] = 0;
			SensorValue[left] = 0;
			wait1Msec(100);
		}
		motor[DriveL] = 0;
		motor[DriveR] = 0;
	}
}

void closeABit() {
	while(SensorValue[in1] > 1000) {
		motor[ClawA] = 50;
		motor[ClawB] = 50;
	}
}

void autoDriveTicksShaft(int masterPower, int left_ticks) { //Drive forward based on sensor values.
	int totalTicks = 0;
	int Autoerror = 0;
	int slavePower = masterPower - 5;
	bool type_drive;

	SensorValue[right] = 0;
	SensorValue[left] = 0;

	if (left_ticks > 0) {
		type_drive = true;
		} else {
		type_drive = false;
	}
	if (type_drive == true) {
		while(abs(totalTicks) < left_ticks) {
			motor[DriveL] = masterPower;
			motor[DriveR] = slavePower;

			Autoerror = (abs(SensorValue[left]) - SensorValue[right]);
			slavePower += Autoerror * 0.5;
			totalTicks += abs(SensorValue[left]);
			SensorValue[right] = 0;
			SensorValue[left] = 0;
			wait1Msec(100);
		}
		motor[DriveL] = 0;
		motor[DriveR] = 0;
	}

	if (type_drive == false) {
		while(totalTicks > left_ticks) {
			motor[DriveL] = masterPower;
			motor[DriveR] = slavePower;

			Autoerror = (SensorValue[left] - SensorValue[right]);
			slavePower += Autoerror * 0.5;
			totalTicks += SensorValue[left];
			SensorValue[right] = 0;
			SensorValue[left] = 0;
			wait1Msec(100);
		}
		motor[DriveL] = 0;
		motor[DriveR] = 0;
	}
}

void clawClose() { // FIX THIS
	int clawValue;
	while(SensorValue[in1] > 1300) {
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;
		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		motor[ClawB] = (600 - claw_r)*-0.05 - claw_d_r*0.2;
		motor[ClawA] = (600 - claw_l)*-0.05 - claw_d_l*0.2;
	}
		motor[ClawA] = 0;
	motor[ClawB] = 0;
}

void deploy() {
	SensorValue[arms_s] = 0;
	while (SensorValue[arms_s] < 150) {
		motor[ArmL1] = 70;
		motor[ArmL2] = 70;
		motor[ArmL3] = 70;
		motor[ArmR1] = 70;
		motor[ArmR2] = 70;
		motor[ArmR3] = 70;
	}
	while (SensorValue[button] == 0) {
		motor[ArmL1] = -70;
		motor[ArmL2] = -70;
		motor[ArmL3] = -70;
		motor[ArmR1] = -70;
		motor[ArmR2] = -70;
		motor[ArmR3] = -70;
	}
	motor[ArmL1] = 0;
	motor[ArmL2] = 0;
	motor[ArmL3] = 0;
	motor[ArmR1] = 0;
	motor[ArmR2] = 0;
	motor[ArmR3] = 0;
}

void hold() {
	while (SensorValue[claw_s] > 623 && SensorValue[claw_s2] < 1817) {
		motor[ClawB] = (SensorValue[claw_s] - 623)/2;
		motor[ClawA] = ((SensorValue[claw_s2] - 1817)/2)*-1;
	}
	motor[ClawB] = 0;
	motor[ClawA] = 0;
}

void autoThrow() { //CHANGE ALL SENSOR VALUES
	SensorValue[arms_s] = 0;
	while(SensorValue[arms_s] < 500) {
		motor[ArmL1] = 127;
		motor[ArmL2] = 127;
		motor[ArmL3] = 127;
		motor[ArmR1] = 127;
		motor[ArmR2] = 127;
		motor[ArmR3] = 127;
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;
		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		motor[ClawB] = (100 - claw_r)*-0.05 - claw_d_r*0.2;
		motor[ClawA] = (100 - claw_l)*-0.05 - claw_d_l*0.2;
	}
	while(SensorValue[arms_s] < 800) {
		motor[ArmL1] = 127;
		motor[ArmL2] = 127;
		motor[ArmL3] = 127;
		motor[ArmR1] = 127;
		motor[ArmR2] = 127;
		motor[ArmR3] = 127;
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;
		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		if(vexRT[Btn7U] == 0)
		{
			motor[ClawB] = (1520 - claw_r)*-0.05 - claw_d_r*0.2;
			motor[ClawA] = (1520 - claw_l)*-0.05 - claw_d_l*0.2;
		}
	}
	motor[ArmL1] = 0;
	motor[ArmL2] = 0;
	motor[ArmL3] = 0;
	motor[ArmR1] = 0;
	motor[ArmR2] = 0;
	motor[ArmR3] = 0;
}

void autoThrowV() { //CHANGE ALL SENSOR VALUES
	SensorValue[arms_s] = 0;
	while(SensorValue[arms_s] < 600) {
		motor[ArmL1] = 127;
		motor[ArmL2] = 127;
		motor[ArmL3] = 127;
		motor[ArmR1] = 127;
		motor[ArmR2] = 127;
		motor[ArmR3] = 127;
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;
		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		motor[ClawB] = (100 - claw_r)*-0.05 - claw_d_r*0.2;
		motor[ClawA] = (100 - claw_l)*-0.05 - claw_d_l*0.2;
	}
	while(SensorValue[arms_s] < 950) {
		motor[ArmL1] = 127;
		motor[ArmL2] = 127;
		motor[ArmL3] = 127;
		motor[ArmR1] = 127;
		motor[ArmR2] = 127;
		motor[ArmR3] = 127;
		int	claw_r = SensorValue[in1] + 0;
		int claw_l = SensorValue[in6] + 50;
		int claw_r_save = claw_r;
		int claw_l_save = claw_l;
		wait1Msec(100);
		int claw_d_r = claw_r - claw_r_save;
		int claw_d_l = claw_l - claw_l_save;
		if(vexRT[Btn7U] == 0)
		{
			motor[ClawB] = (1520 - claw_r)*-0.05 - claw_d_r*0.2;
			motor[ClawA] = (1520 - claw_l)*-0.05 - claw_d_l*0.2;
		}
	}
	motor[ArmL1] = 0;
	motor[ArmL2] = 0;
	motor[ArmL3] = 0;
	motor[ArmR1] = 0;
	motor[ArmR2] = 0;
	motor[ArmR3] = 0;
}

task battery()
{
	bLCDBacklight = true;									// Turn on LCD Backlight
	string mainBattery, backupBattery;

	while(SensorValue[button] == 0)														// An infinite loop to keep the program running until you terminate it
	{
		clearLCDLine(0);											// Clear line 1 (0) of the LCD
		clearLCDLine(1);											// Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Backup: ");
		sprintf(backupBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');	//Build the value to be displayed
		displayNextLCDString(backupBattery);

		//Short delay for the LCD refresh rate
		wait1Msec(100);
	}
}


task codeChooser () {
	//Declare count variable to keep track of our choice
	//Clear LCD

	clearLCDLine(0);
	clearLCDLine(1);
	//Loop while center button is not pressed
	while(nLCDButtons != centerButton)
	{
		//Switch case that allows the user to choose from 4 different options
		switch(count){
		case 0:
			//Display first choice
			displayLCDCenteredString(0, "Cube and Stars");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count = 4;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 1:
			//Display second choice
			displayLCDCenteredString(0, "Stars Fence");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 2:
			//Display third choice
			displayLCDCenteredString(0, "Just Cube");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 3:
			//Display fourth choice
			displayLCDCenteredString(0, "Autonomous 4");
			displayLCDCenteredString(1, "<		 Enter		>");
			waitForPress();
			//Increment or decrement "count" based on button press
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count++;
			}
			break;
		case 4:
			//Display fourth choice
			startTask(battery);
			if(nLCDButtons == leftButton)
			{
				waitForRelease();
				count--;
			}
			else if(nLCDButtons == rightButton)
			{
				waitForRelease();
				count = 0;
			}
			break;
		default:
			count = 0;
			break;
		}
	}
}

void pre_auton()
{

}

task autonomous()
{
	clearLCDLine(0);
	clearLCDLine(1);
	//Switch Case that actually runs the user choice
	switch(count){
	case 0:
		//If count = 0, run the code correspoinding with choice 1
		displayLCDCenteredString(0, "Cube and Stars");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(1000);						// Robot waits for 2000 milliseconds

		// INSERT AUTONOMOUS 1 CODE HERE BEFORE BREAK
		// Cube and Stars Autonomous
		//
		deploy();
		autoDriveTicksShaft(60,150);
		clawOpen();
		wait1Msec(200);
		gyro_turnManitha(-850);
		autoDriveTicksShaft(100, 360);
		clawClose();
		wait1Msec(750);
		CubeTurn(-900);
		autoDriveTicksShaftPower(-100, -100);
		autoThrow();
		autoDownMove(70,150);
		clawOpen();
		autoDriveTicksShaft(50, 110);
		closeABit();
		wait1Msec(750);
		autoDriveTicksShaftPower(-100,-500);
		autoThrowV();
		while(true) {
			int	claw_r = SensorValue[in1] + 0;
			int claw_l = SensorValue[in6] + 50;
			int claw_r_save = claw_r;
			int claw_l_save = claw_l;
			wait1Msec(100);
			int claw_d_r = claw_r - claw_r_save;
			int claw_d_l = claw_l - claw_l_save;
			motor[ClawB] = (1520 - claw_r)*-0.05 - claw_d_r*0.2;
			motor[ClawA] = (1520 - claw_l)*-0.05 - claw_d_l*0.2;
		}
		//END OF FIRST AUTONOMOUS
		break;
	case 1:
		//If count = 1, run the code correspoinding with choice 2
		displayLCDCenteredString(0, "Stars off Fence");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(200);						// Robot waits for 2000 milliseconds

		// INSERT AUTONOMOUS 2 CODE HERE BEFORE BREAK
		// Three Stars off of the fence
		deploy();
		gyro_turnManitha(115);
		clawOpen();
		wait1Msec(1000);
		threeStars(100, 630);
		break;
	case 2:
		//If count = 2, run the code correspoinding with choice 3
		displayLCDCenteredString(0, "Just Cube");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(1000);						// Robot waits for 2000 milliseconds

		//INSERT AUTONOMOUS 3 CODE HERE BEFORE BREAK
		// Just the cube
		deploy();
		autoDriveTicksShaft(60,150);
		clawOpen();
		wait1Msec(200);
		gyro_turnManitha(-850);
		autoDriveTicksShaft(100, 360);
		clawClose();
		wait1Msec(300);
		CubeTurn(-900);
		autoDriveTicksShaftPower(-100, -100);
		autoThrow();
		clawOpen();
		break;
	case 3:
		//If count = 3, run the code correspoinding with choice 4
		displayLCDCenteredString(0, "Autonomous 4");
		displayLCDCenteredString(1, "is running!");
		wait1Msec(1000);						// Robot waits for 2000 milliseconds

		//INSERT AUTONOMOUS 4 CODE HERE BEFORE BREAK
		// unknown

		break;
	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!");
		break;
	}
}

task usercontrol()
{
	startTask(arm);
	startTask(drive);
	startTask(codeChooser);
	startTask(clawControl);
	while (true)
	{
		motor[ArmR1] = arms;
		motor[ArmR2] = arms;
		motor[ArmR3] = arms;
		motor[ArmL1] = arms;
		motor[ArmL2] = arms;
		motor[ArmL3] = arms;
	}
}
